### PR TITLE
Make footer smaller

### PR DESCRIPTION
**Pull request by jlntrt**
- 50 % smaller
- 3 columns
- GPG ID in groups of 4 chars
- background a bit darker than main part
- margin improvements
- white font color
- credits align right

### CODE REVIEW

**Comment by sphinxc0re** [comment]
Could you right-align the credits link?

**Comment by jlntrt** [comment]
did it. ;)

**Comment by zaolin** [comment]
Can you align all text left and make a right margin around 35px. Increase the font size to the maximum and add a button for the credits link

**Comment by jlntrt** [comment]
@zaolin would look like this? rly?
screenshot from 2017-01-17 20-06-32

**Comment by zaolin** [comment]
if you have a better idea but make the font size bigger

**Comment by K4stor** [comment]
Didn't we ban that green color ?

**Comment by jlntrt** [comment]
Would like to keep it simple like: screenshot from 2017-01-17 23-53-59

**Comment by zaolin** [comment]
font weight bold if possible then we can merge it

**Comment by jlntrt** [comment]
@zaolin done. :+1:

**Pull request merged**
