### PR TITLE
Footer

### LINKED ISSUE #26: Add footer to each slide page
Hey,

we should use a footer for showing the coreboot builder email, gpg key id and the credits page.
Pad told me that it would be nice if this done by text based footer only.

### PR DESCRIPTION
**Pull request by jlntrt**
Here is the first version of the footer. It is small as possible and responsive as possible.

closes #26

### CODE REVIEW

**Comment by sphinxc0re** [comment]
I'm not too sure about the font color. I guess it would look much better in black. Also, you can remove the titles for the columns and remove both of them to move everything to the left side.

**Review by sphinxc0re — CHANGES_REQUESTED** [review]
Please use the color classes shipped by the framework

**Comment by sphinxc0re** [comment]
@juliandortmund please rebase onto the current master and fix the resulting conflicts

**Comment by jlntrt** [comment]
Done.

**Review by sphinxc0re — APPROVED** [review]

**Comment by sphinxc0re** [comment]
Please rebase and squash onto current master @juliandortmund

**Comment by jlntrt** [comment]
Rebased and sqashed :white_check_mark:

**Comment by sphinxc0re** [comment]
@juliandortmund 4664d93db0f779af461fc1da333bb69611227631 fixes footer color and shadow

**Pull request merged**
